blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
      path('', views.post_list_view, name='post_list_view'),
      path('post/<post_id>/', views.post_detail_view, name="post_detail_view"),
      path('author/<author_name>/', views.post_list_view, name="post_list_author"),
      path('category/<category_name>/', views.post_list_view, name="post_list_category")
]

covid19/urls.py
from django.urls import path
from . import views

app_name = 'covid19'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('<source>/', views.index_view, name='index'),
]

myapp/urls.py
from django.urls import path

from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('start/', views.home_view, name='start'),
    path('contact/', views.contact_view, name='contact'),
    path('about/', views.about_view, name='about'),
    path('about-me/', views.about_view, name='about-me'),
    path('genbank/', views.genbank_view, name='genbank'),    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('news/', include('news.urls')),
    path('covid19/', include('covid19.urls')),
    path('blog/', include('blog.urls')),
]

news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('<source>/', views.index_view, name='index'),
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length = 50, default = "")

    class Meta:
        verbose_name_plural = 'authors'


    def __str__(self):
        return self.name

class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=140)
    body = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    date_publish = models.DateTimeField(blank=True, null=True)
    public = models.BooleanField(default=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)
    # author = models.CharField(max_length=30, default="")

    def __str__(self):
        return self.title

covid19/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Post, Author

def post_list_view(request, category_name=None, author_name=None):

    if category_name:
        queryset = Post.objects.filter(category__name=category_name)
    elif author_name:
        queryset = Post.objects.filter(author__name=author_name)
    else:
        queryset = Post.objects.all()

    context = {
        'object_list': queryset.filter(public=True).order_by('-date_publish'),
        'category_list': Category.objects.all(),
        'category_name': category_name,
        'author_name' : author_name,
        
    }
    return render(request, 'blog/post_list.html', context)


def post_detail_view(request, post_id):
    context = {
        'object': get_object_or_404(Post, id=post_id),
        'category_list': Category.objects.all(),
        'category_name': None,       
    }
    return render(request, 'blog/post_detail.html', context)

covid19/views.py
from datetime import datetime
import requests
from django.shortcuts import render

def index_view(request, source='PL'):
    
    #Statistics
    url = ('https://api.covid19api.com/summary')
    response = requests.get(url)
    data = response.json()

    for record in data['Countries']:
        if record['CountryCode'] == source:
            completeCountry = record
    
    completeGlobal = data['Global']
    
    #chetny
    updatedTimeGlobal = datetime.strptime(completeGlobal["Date"], "%Y-%m-%dT%H:%M:%S.%fZ")
    updatedTimeCountry = datetime.strptime(completeCountry["Date"], "%Y-%m-%dT%H:%M:%S.%fZ")


    countries = {
    'PL': 'Poland', 
    'DE': 'Germany',
    'US': 'USA',
    'GB': 'Great Britain',
    'FR': 'France',
    'ES': 'Spain',
    'RU': 'Russia',
    }


    context = {
        'statistics': completeCountry,
        'statisticsGlobal': completeGlobal,
        'Countries': countries,
        'activeSource': source,        
        'updatedTimeGlobal': updatedTimeGlobal,
        'updatedTimeCountry': updatedTimeCountry,
    }
    return render(request, 'covid19/index.html', context)

myapp/views.py
import random
import urllib.request

from django.shortcuts import render


def home_view(request):
    number = random.randint(1, 100)
    some_list = [
      random.randint(1, 100),
      random.randint(1, 100),
      random.randint(1, 100),
    ]
    some_dict = {
      'A': 1,
      'B': 2,
      'C': 3
    }
    context = {
      'mynumber': number,
      'bool_item': True,
      'some_list': some_list,
      'some_dict': some_dict,
    }
    return render(request, 'myapp/index.html', context)


def about_view(request):
    mytech = [
        {
          'name': 'HTML',
          'url': 'https://www.w3schools.com/html/',
          'level': 'beginner'
        },
        {
          'name': 'CSS',
          'url': 'https://www.w3schools.com/css/',
          'level': 'beginner'
        },
        {
          'name': 'Bootstrap',
          'url': 'https://getbootstrap.com',
          'level': 'beginner'
        },
        {
          'name': 'Python',
          'url': 'https://www.python.org',
          'level': 'intermediate'
        },
        {
          'name': 'Django',
          'url': 'https://www.djangoproject.com',
          'level': 'beginner'      
        },    
    ]
    context = {
        'lucky_number': random.randint(1, 10),
        'unlucky_number': random.randint(1, 10),
        'mytech': mytech, 
    }
    return render(request, 'myapp/about.html', context)


def contact_view(request):
    return render(request, 'myapp/contact.html')


def genbank_view(request):
    URL = 'ftp://ftp.ncbi.nlm.nih.gov/genbank/README.genbank'
    response = urllib.request.urlopen(URL)
    data = response.read() 
    text = data.decode('utf-8')
    release = text.split('\n')[2]
    date = text.split('\n')[9]
    context = {
      'gb_release' : release.strip().split()[4],
      'gb_date' : " ".join(date.strip().split()[1:5])
    }
    return render(request, 'myapp/genbank.html', context)

news/views.py
import requests
from . import config
from django.shortcuts import render

SOURCES = [
  {'id': 'new-scientist', 'name': 'The New Scientist'},
  {'id': 'techradar', 'name': 'TechRadar'},
  {'id': 'national-geographic', 'name': 'National Geographic'},
  {'id': 'ars-technica', 'name': 'Ars Technica'},
  {'id': 'mashable', 'name': 'Mashable'},
]

def index_view(request, source='new-scientist'):
    API_KEY = config.api_key
    url = ('https://newsapi.org/v2/everything?'
           f'sources={source}&'
           f'apiKey={API_KEY}')

    response = requests.get(url)
    data = response.json()
    context = {
      'newsapi': data,
      'sources': SOURCES,
      'active_source': source
    }
    #print(data['articles'][0]['author'])
    return render(request, 'news/index.html', context)

blog/templates/blog/includes/category_widget.html
<!-- Category list -->
{% if category_name %}
  <a href="{% url 'blog:post_list_view' %}">All</a>
{% else %}
  All
{% endif %} |

{% for category in category_list %}
   {% if category.name == category_name %}
     {{ category.name }}
   {% else %}
     <a href="{% url 'blog:post_list_category' category.name %}">{{ category }}</a>
   {% endif %}
   |
{% endfor %}
<!-- /Category list -->
<br><br>

blog/templates/blog/post_detail.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block page_title %}Blog{% endblock %}
{% block nav-link-blog %}active{% endblock %}

{% block content %}
    
    <h1 class="mt-5">Blog Post</h1>

    {% include 'blog/includes/category_widget.html' with category_name=category_name category_list=category_list %}


 <!-- begin::Post -->
    <div class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">        
        <h5 class="mb-1">{{ object.title|title }}</h5>        
        <small>Published: {{ object.date_publish|timesince }} ago</small>
      </div>
      <p class="mb-1 md2html">{{ object.body|safe }}</p>
      <div class="d-flex w-100 justify-content-between">
        <small> Updated: {{ object.date_update }} </small>
        <small> Written by: 
            <a href="{% url 'blog:post_list_author' object.author.name %}">{{ object.author.name }}</a>
        </small>
      </div>
    </div>
    <!-- end::Post -->

{% endblock %}

blog/templates/blog/post_detail_my.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block page_title  %}Blog{% endblock %}
{% block nav-link-blog %}active{% endblock %}

{% block page_level_css %}
<!-- Blog theme-->
<link href="{% static 'blog/css/styles.css' %}" rel="stylesheet">
<!-- Bootstrap Blog -->   
<link rel="icon" type="image/x-icon" href="{% static 'blog/assets/favicon.ico' %}" />
<!-- Google fonts-->
<link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}    


        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'blog/assets/img/home-bg.jpg' %}')";>


            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
            {% include 'blog/includes/category_widget.html' with category_name=category_name category_list=category_list %}
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-preview">
                        <a href="post.html">
                            <h2 class="post-title">{{object.title|title}}</h2>
                        </a>
                        <h3 class="post-subtitle">{{object.body|safe}} </h3>
                        
                        <p class="post-meta">
                            Posted by
                            <a href="{% url 'blog:post_list_author' object.author.name %}">{{ object.author.name }}</a>
                            {{ object.date_publish }} ({{ object.date_publish|timesince }} ago)
                        </p>
                        <p> {{object.data_create}}</p>
                    </div>
                    
                            
                    
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>          

        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>

    </body>
</html>

{%endblock%}

blog/templates/blog/post_list.html
{% extends 'myapp/base.html' %}

{% block page_title %}Blog{% endblock %}
{% block nav-link-blog %}active{% endblock %}

{% block content %}
    
    <h1 class="mt-5">Blog</h1>

    {% include 'blog/includes/category_widget.html' with category_name=category_name category_list=category_list %}

    <div class="alert alert-info" role="alert">
      Showing <strong>{{ object_list|length }}</strong> post{{ object_list|pluralize}} {% if category_name %}from <strong>{{ category_name }}</strong>{% else %}.{% endif %}
    </div>


    {% if object_list %}
      <div class="list-group">
      {% for obj in object_list %}
        <!-- begin::Post -->
        <div class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <a href="{% url 'blog:post_detail_view' obj.id %}">
              <h5 class="mb-1">{{ obj.title|title }}</h5>
            </a>
            <small>Published: {{ obj.date_publish|timesince }} ago</small>
          </div>
          <a href="{% url 'blog:post_detail_view' obj.id %}"><p class="mb-1 md2html">{{ obj.body|safe|truncatewords_html:20 }} ...</p></a>
          <div class="d-flex w-100 justify-content-between">
            <small>Updated: {{ obj.date_update }}</small>
            <small>
              Written by: 
              <a href="{% url 'blog:post_list_author' obj.author.name %}">{{ obj.author.name }}</a> 
            </small>
          </div>
        </div>
        <!-- end::Post -->
      {% endfor %}
      </div>
    {% else %}
      <div class="alert alert-primary" role="alert">No posts to show.</div>
    {% endif %}

{% endblock %}

myapp/templates/covid19/index.html
```{% extends 'myapp/base.html' %}
{% load static %}
{% block page_title %}Covid19{% endblock %}
{% block nav-link-covid19 %}active{% endblock %}


{% block content %}



<div class = "bg-primary bg-gradient col-sm-6 m-1 ">
  <h1 class="text-light p-3 text-opacity-75"> Covid19 Summary</h1><br>
</div>


{% for key, value in Countries.items %}  
  {% if key == activeSource %}
    <a href="{% url 'covid19:index' key %}" class=" bg-primary btn m-1 mt-2 mb-2" > {{ value }} </a>
  {% elif key != activeSource %}
    <a href="{% url 'covid19:index' key %}" class=" bg-primary btn bg-gradient bg-opacity-75 m-1 mt-2 mb-2" > {{ value }} </a>  
  {% endif %}
   
{% endfor %}

<div class="container" style = "display: flex;">
      <div class="card" style="width: 18rem;">
        <div class="bg-primary card-header bg-gradient bg-opacity-75">
          <h3>Global</h3>
        </div>
        <ul class="list-group list-group-flush">
          <li class="bg-warning list-group-item bg-opacity-50"><b>NewConfirmed:</b> {{ statisticsGlobal.NewConfirmed }}</li>
          <li class="bg-warning list-group-item" style="--bs-bg-opacity: .9;"><b>TotalConfirmed:</b> {{ statisticsGlobal.TotalConfirmed }}</li>
          <li class="bg-danger list-group-item bg-opacity-50"><b>NewDeaths:</b> {{ statisticsGlobal.NewDeaths }}</li>
          <li class="bg-danger list-group-item bg-opacity-75"><b>TotalDeaths:</b> {{ statisticsGlobal.TotalDeaths }}</li>
          <li class="bg-success list-group-item bg-opacity-50"><b>NewRecovered:</b> {{ statisticsGlobal.NewRecovered }}</li>
          <li class="bg-success list-group-item bg-opacity-75"><b>TotalRecovered:</b> {{ statisticsGlobal.TotalRecovered }}</li>
          <li class="list-group-item bg-light"><b>Date:</b> {{ statisticsGlobal.Date }}</li>
          <li class="list-group-item list-group-item-info">Updated {{ updatedTimeGlobal|timesince }} ago</li>
        </ul>    
    </div>
      <div class="card" style="width: 18rem;">
        <div class="bg-primary card-header bg-gradient bg-opacity-50">
          <h3>{{ statistics.Country }}</h3>
        </div>
        <ul class="list-group list-group-flush">
          <li class="bg-warning list-group-item bg-opacity-50"><b>NewConfirmed:</b> {{ statistics.NewConfirmed }}</li>
          <li class="bg-warning list-group-item" style="--bs-bg-opacity: .9;"><b>TotalConfirmed:</b> {{ statistics.TotalConfirmed }}</li>
          <li class="bg-danger list-group-item bg-opacity-50"><b>NewDeaths:</b> {{ statistics.NewDeaths }}</li>
          <li class="bg-danger list-group-item bg-opacity-75"><b>TotalDeaths:</b> {{ statistics.TotalDeaths }}</li>
          <li class="bg-success list-group-item bg-opacity-50"><b>NewRecovered:</b> {{ statistics.NewRecovered }}</li>
          <li class="bg-success list-group-item bg-opacity-75"><b>TotalRecovered:</b> {{ statistics.TotalRecovered }}</li>
          <li class="list-group-item bg-light"><b>Date:</b> {{ statistics.Date }}</li>
          <li class="list-group-item list-group-item-info">Updated {{ updatedTimeCountry|timesince }} ago</li>
        </ul>
  </div>
</div>






	
{% endblock %}```

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block page_title %}About{% endblock %}
{% block nav-link-about %}active{% endblock %}

{% block content %}
    
    <h1 class="mt-5">About</h1>

    <!-- Lucky and unlucky numbers -->
    {% if lucky_number != unlucky_number %}
    <p>Lucky number: <b>{{ lucky_number }}</b></p>
    <p>Unlucky number: <b>{{ unlucky_number }}</b></p>
    {% else %}
    <p>Don’t worry, be happy!</p>
    {% endif %}
    <!-- /Lucky and unlucky numbers -->

    <!-- Mytech -->
    <ul>
      {% for lang in mytech %}
      <li>
        <a href="{{ lang.url }}">{{ lang.name }}</a>: {{ lang.level }}
      </li>
      {% endfor %}
    </ul>
    <!-- /Mytech -->
    
{% endblock %}

myapp/templates/myapp/base.html
{% load static %}

<!doctype html>
<html class="h-100">
  <head>
    <title>My project | {% block page_title %}{% endblock %}</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">    
          
    <!-- My custom CSS -->
    <link rel="stylesheet" href="{% static 'myapp/css/style.css' %}">
    
    {% block page_level_css %}
    {% endblock %}

  </head>
  <body class="d-flex flex-column h-100">


    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'myapp:home' %}">
            <img src="{% static 'myapp/img/fa-home.svg' %}" height="30px"> Website
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link {% block nav-link-home %}{% endblock %}" aria-current="page" href="{% url 'myapp:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block nav-link-news %}{% endblock %}" href="{% url 'news:index' %}">News</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block nav-link-covid19 %}{% endblock %}" href="{% url 'covid19:index' %}">Covid19</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block nav-link-genbank %}{% endblock %}" href="{% url 'myapp:genbank' %}">Genbank</a>
              </li>       
              <li class="nav-item">
                <a class="nav-link {% block nav-link-blog %}{% endblock %}" href="{% url 'blog:post_list_view' %}">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block nav-link-about %}{% endblock %}" href="{% url 'myapp:about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block nav-link-contact %}{% endblock %}" href="{% url 'myapp:contact' %}">Contact</a>
              </li>              
            </ul>
            <!--<form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>-->
          </div>
        </div>
      </nav>
    </header>

    <!-- Main -->
    <main class="flex-shrink-0">
      <div class="container">
        {% block content %}
        <p>Default content</p>
        {% endblock %}
      </div>
    </main>
    <!-- /Main -->

    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-light">
      <div class="container">
        <span>© 2021 Company, Inc. · 
        <a href="#">Facebook</a> · 
        <a href="#">Twitter</a>
        </span>
      </div>
    </footer>
    <!-- /Footer -->
    
    <!-- Javascripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.1/showdown.min.js"></script>
    <script>
      var converter = new showdown.Converter();
      var elements = document.getElementsByClassName("md2html");
      for(var i = 0; i < elements.length; i++) {
        var text = elements[i].innerHTML;
        elements[i].innerHTML = converter.makeHtml(text);
      }

    </script>
  </body>
</html>

myapp/templates/myapp/contact.html
{% extends 'myapp/base.html' %}

{% block page_title %}Contact{% endblock %}
{% block nav-link-contact %}active{% endblock %}

{% block content %}
    
    <h1 class="mt-5">Contact</h1>
    <p>This is contact page.</p>
    {{ block.super }}

    {% include 'myapp/includes/widget.html' %}

{% endblock %}

myapp/templates/myapp/genbank.html
{% extends 'myapp/base.html' %}

{% block content %}

    <h1>Genbank</h1>
    <p>Release: <b>{{ gb_release }}</b></p>
    <p>Date: <b>{{ gb_date }}</b></p>
    
{% endblock %}

myapp/templates/myapp/includes/widget.html
<div style="height:50px;width:100%;background-color:grey;">
  <p>A widget goes here.</p>
</div>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block page_title %}Home{% endblock %}
{% block nav-link-home %}active{% endblock %}


{% block content %}
    
    <h1 class="mt-5">Home</h1>
    <p>This is my home page</p>

    <img src="{% static 'myapp/img/django-logo.png' %}" width="200px" alt="Django logo" />

    <!-- Random number -->
    {% if bool_item %}
      <p>Random number is: {{mynumber}}</p>
      {% if mynumber == 7 %}
        <p>Damn, you are lucky!</p>
      {% elif mynumber == 13 %}
        <p>You have no luck!</p>
      {% endif %}
    {% endif %}
    <!-- /Random number -->

    <!-- List of items --> 
    <p>You have <b>{{some_list|length}}</b> items:<br>
    <ul>
      {% for some_item in some_list %}
      <li>{{some_item}}</li>
      {% endfor %}
    </ul>
    <!-- /List of items -->


{% endblock %}

news/templates/news/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block page_title %}News{% endblock %}
{% block nav-link-news %}active{% endblock %}
{% block page_level_css %}
  <link rel="stylesheet" href="{% static 'news/css/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="mt-5">News</h1>
<!-- Sources menu -->
{% for source in sources %}
  {% if source.id != active_source %}
    <a href="{% url 'news:index' source.id %}">{{ source.name }}</a>
  {% else %}
    {{ source.name }}
  {% endif %} |    
{% endfor %}
<br><br>
<!-- /Sources menu -->

{% if newsapi.status == 'ok' %}
<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for article in newsapi.articles %}
  <!-- Article -->
  <div class="col">
    <div class="card h-100">
      <img src="{{ article.urlToImage }}" class="card-img-top" alt="{{ article.title }}">
      <div class="card-body">
        <h5 class="card-title">
          <a href="{{ article.url }}" target="_blank">{{ article.title }}</a>
        </h5>
        <p class="card-text">{{ article.description }}</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">{{ article.publishedAt }}</small>
      </div>
    </div>
  </div>
  <!-- /Article -->
  {% endfor %}
</div>
{% endif %}
{% endblock %}